/**
 * Do not edit directly, this file was auto-generated
 * by tokens/build.mjs from tokens/input/ (level: theme).
 */
export declare const background: {
    readonly brand: {
        readonly subtle: "var(--background-brand-subtle)";
        readonly solid: "var(--background-brand-solid)";
        readonly solidHover: "var(--background-brand-solid-hover)";
        readonly solidActive: "var(--background-brand-solid-active)";
        readonly alpha10: "var(--background-brand-alpha-10)";
        readonly alpha20: "var(--background-brand-alpha-20)";
        readonly alpha30: "var(--background-brand-alpha-30)";
        readonly alpha40: "var(--background-brand-alpha-40)";
        readonly alpha50: "var(--background-brand-alpha-50)";
        readonly alpha60: "var(--background-brand-alpha-60)";
        readonly alpha70: "var(--background-brand-alpha-70)";
        readonly alpha80: "var(--background-brand-alpha-80)";
        readonly alpha90: "var(--background-brand-alpha-90)";
    };
    readonly success: {
        readonly subtle: "var(--background-success-subtle)";
        readonly solid: "var(--background-success-solid)";
        readonly solidHover: "var(--background-success-solid-hover)";
        readonly solidActive: "var(--background-success-solid-active)";
        readonly alpha10: "var(--background-success-alpha-10)";
        readonly alpha20: "var(--background-success-alpha-20)";
        readonly alpha30: "var(--background-success-alpha-30)";
        readonly alpha40: "var(--background-success-alpha-40)";
        readonly alpha50: "var(--background-success-alpha-50)";
        readonly alpha60: "var(--background-success-alpha-60)";
        readonly alpha70: "var(--background-success-alpha-70)";
        readonly alpha80: "var(--background-success-alpha-80)";
        readonly alpha90: "var(--background-success-alpha-90)";
    };
    readonly warning: {
        readonly subtle: "var(--background-warning-subtle)";
        readonly solid: "var(--background-warning-solid)";
        readonly solidHover: "var(--background-warning-solid-hover)";
        readonly solidActive: "var(--background-warning-solid-active)";
        readonly alpha10: "var(--background-warning-alpha-10)";
        readonly alpha20: "var(--background-warning-alpha-20)";
        readonly alpha30: "var(--background-warning-alpha-30)";
        readonly alpha40: "var(--background-warning-alpha-40)";
        readonly alpha50: "var(--background-warning-alpha-50)";
        readonly alpha60: "var(--background-warning-alpha-60)";
        readonly alpha70: "var(--background-warning-alpha-70)";
        readonly alpha80: "var(--background-warning-alpha-80)";
        readonly alpha90: "var(--background-warning-alpha-90)";
    };
    readonly danger: {
        readonly subtle: "var(--background-danger-subtle)";
        readonly solid: "var(--background-danger-solid)";
        readonly solidHover: "var(--background-danger-solid-hover)";
        readonly solidActive: "var(--background-danger-solid-active)";
        readonly alpha10: "var(--background-danger-alpha-10)";
        readonly alpha20: "var(--background-danger-alpha-20)";
        readonly alpha30: "var(--background-danger-alpha-30)";
        readonly alpha40: "var(--background-danger-alpha-40)";
        readonly alpha50: "var(--background-danger-alpha-50)";
        readonly alpha60: "var(--background-danger-alpha-60)";
        readonly alpha70: "var(--background-danger-alpha-70)";
        readonly alpha80: "var(--background-danger-alpha-80)";
        readonly alpha90: "var(--background-danger-alpha-90)";
    };
    readonly accent: {
        readonly subtle: "var(--background-accent-subtle)";
        readonly solid: "var(--background-accent-solid)";
        readonly solidHover: "var(--background-accent-solid-hover)";
        readonly solidActive: "var(--background-accent-solid-active)";
        readonly alpha10: "var(--background-accent-alpha-10)";
        readonly alpha20: "var(--background-accent-alpha-20)";
        readonly alpha30: "var(--background-accent-alpha-30)";
        readonly alpha40: "var(--background-accent-alpha-40)";
        readonly alpha50: "var(--background-accent-alpha-50)";
        readonly alpha60: "var(--background-accent-alpha-60)";
        readonly alpha70: "var(--background-accent-alpha-70)";
        readonly alpha80: "var(--background-accent-alpha-80)";
        readonly alpha90: "var(--background-accent-alpha-90)";
    };
    readonly neutral: {
        readonly subtle: "var(--background-neutral-subtle)";
        readonly solid: "var(--background-neutral-solid)";
        readonly solidHover: "var(--background-neutral-solid-hover)";
        readonly solidActive: "var(--background-neutral-solid-active)";
        readonly alpha10: "var(--background-neutral-alpha-10)";
        readonly alpha20: "var(--background-neutral-alpha-20)";
        readonly alpha30: "var(--background-neutral-alpha-30)";
        readonly alpha40: "var(--background-neutral-alpha-40)";
        readonly alpha50: "var(--background-neutral-alpha-50)";
        readonly alpha60: "var(--background-neutral-alpha-60)";
        readonly alpha70: "var(--background-neutral-alpha-70)";
        readonly alpha80: "var(--background-neutral-alpha-80)";
        readonly alpha90: "var(--background-neutral-alpha-90)";
    };
    readonly info: {
        readonly subtle: "var(--background-info-subtle)";
        readonly solid: "var(--background-info-solid)";
        readonly solidHover: "var(--background-info-solid-hover)";
        readonly solidActive: "var(--background-info-solid-active)";
        readonly alpha10: "var(--background-info-alpha-10)";
        readonly alpha20: "var(--background-info-alpha-20)";
        readonly alpha30: "var(--background-info-alpha-30)";
        readonly alpha40: "var(--background-info-alpha-40)";
        readonly alpha50: "var(--background-info-alpha-50)";
        readonly alpha60: "var(--background-info-alpha-60)";
        readonly alpha70: "var(--background-info-alpha-70)";
        readonly alpha80: "var(--background-info-alpha-80)";
        readonly alpha90: "var(--background-info-alpha-90)";
    };
};
export declare const border: {
    readonly subtle: "var(--border-subtle)";
    readonly default: "var(--border-default)";
    readonly strong: "var(--border-strong)";
    readonly brandSubtle: "var(--border-brand-subtle)";
    readonly successSubtle: "var(--border-success-subtle)";
    readonly warningSubtle: "var(--border-warning-subtle)";
    readonly dangerSubtle: "var(--border-danger-subtle)";
    readonly accentSubtle: "var(--border-accent-subtle)";
    readonly brand: "var(--border-brand)";
    readonly accent: "var(--border-accent)";
    readonly success: "var(--border-success)";
    readonly warning: "var(--border-warning)";
    readonly danger: "var(--border-danger)";
    readonly neutral: "var(--border-neutral)";
};
export declare const button: {
    readonly brand: "var(--button-brand)";
    readonly brandHover: "var(--button-brand-hover)";
    readonly brandPressed: "var(--button-brand-pressed)";
    readonly brandFocus: "var(--button-brand-focus)";
    readonly brandFocusRing: "var(--button-brand-focus-ring)";
    readonly brandDisabled: "var(--button-brand-disabled)";
    readonly awake: "var(--button-awake)";
    readonly awakeHover: "var(--button-awake-hover)";
    readonly awakePressed: "var(--button-awake-pressed)";
    readonly awakeFocus: "var(--button-awake-focus)";
    readonly awakeFocusRing: "var(--button-awake-focus-ring)";
    readonly awakeDisabled: "var(--button-awake-disabled)";
    readonly danger: "var(--button-danger)";
    readonly dangerHover: "var(--button-danger-hover)";
    readonly dangerPressed: "var(--button-danger-pressed)";
    readonly dangerFocus: "var(--button-danger-focus)";
    readonly dangerFocusRing: "var(--button-danger-focus-ring)";
    readonly dangerDisabled: "var(--button-danger-disabled)";
    readonly neutral: "var(--button-neutral)";
    readonly neutralHover: "var(--button-neutral-hover)";
    readonly neutralPressed: "var(--button-neutral-pressed)";
    readonly neutralFocus: "var(--button-neutral-focus)";
    readonly neutralFocusRing: "var(--button-neutral-focus-ring)";
    readonly neutralDisabled: "var(--button-neutral-disabled)";
};
export declare const icon: {
    readonly primary: "var(--icon-primary)";
    readonly secondary: "var(--icon-secondary)";
    readonly tertiary: "var(--icon-tertiary)";
    readonly quaternary: "var(--icon-quaternary)";
    readonly inverse: "var(--icon-inverse)";
    readonly link: "var(--icon-link)";
    readonly brand: "var(--icon-brand)";
    readonly accent: "var(--icon-accent)";
    readonly success: "var(--icon-success)";
    readonly warning: "var(--icon-warning)";
    readonly danger: "var(--icon-danger)";
    readonly info: "var(--icon-info)";
    readonly muted: "var(--icon-muted)";
    readonly disabled: "var(--icon-disabled)";
};
export declare const text: {
    readonly primary: "var(--text-primary)";
    readonly secondary: "var(--text-secondary)";
    readonly tertiary: "var(--text-tertiary)";
    readonly quaternary: "var(--text-quaternary)";
    readonly inverse: "var(--text-inverse)";
    readonly link: "var(--text-link)";
    readonly brand: "var(--text-brand)";
    readonly accent: "var(--text-accent)";
    readonly success: "var(--text-success)";
    readonly warning: "var(--text-warning)";
    readonly danger: "var(--text-danger)";
    readonly info: "var(--text-info)";
    readonly muted: "var(--text-muted)";
    readonly disabled: "var(--text-disabled)";
};
type Leaves<T> = T extends string ? T : {
    [K in keyof T]: Leaves<T[K]>;
}[keyof T];
export type ThemeToken = Leaves<typeof background | typeof border | typeof button | typeof icon | typeof text>;
export {};
