/**
 * Do not edit directly — generated by scripts/build-resume-icons.mjs
 * from src/Atoms/ResumeIcon/assets/enhancv-outline.
 */
import type { ResumeIconSetData } from "../types";
export declare const enhancvOutline: ResumeIconSetData;
