/**
 * Do not edit directly — generated by scripts/build-resume-icons.mjs
 * from src/Atoms/ResumeIcon/assets/enhancv-filled.
 */
import type { ResumeIconSetData } from "../types";
export declare const enhancvFilled: ResumeIconSetData;
