import React from "react";
import type { IconsUiId } from "./fonts/ui/icons-ui";
import type { TextColorToken } from "../../types/tokens";
/** Name union per icon set — each generated by scripts/build-icon-font.sh. */
interface IconNameBySet {
    ui: IconsUiId;
}
export type IconSet = keyof IconNameBySet;
export type UiIconName = IconNameBySet["ui"];
export type IconProps<S extends IconSet = "ui"> = {
    name: IconNameBySet[S];
    /** Icon set the name belongs to. */
    set?: S;
    /** Glyph size in px (sets font-size). Inherits the surrounding font-size when omitted. */
    size?: number;
    /** Theme text colour. Inherits the surrounding colour (currentColor) when omitted. */
    color?: TextColorToken;
} & Omit<React.HTMLAttributes<HTMLElement>, "children" | "color">;
/**
 * Icon-font glyph. Sized by `size`/font-size, colored by `color`/currentColor;
 * decorative by default (aria-hidden) — pass aria-hidden={false} plus a label
 * on the parent control when the icon is the only content.
 */
export declare const Icon: <S extends IconSet = "ui">(props: IconProps<S> & {
    ref?: React.Ref<HTMLElement>;
}) => React.ReactElement;
export {};
