import React from "react";
import type { IconsUiId } from "./fonts/ui/icons-ui";
import type { TextColorToken } from "../../types/tokens";
/** Generated by scripts/build-icon-font.sh from src/Atoms/Icon/assets/ui. */
export type UiIconName = IconsUiId;
export type IconProps = {
    name: UiIconName;
    /** Glyph size in px (sets font-size). Inherits the surrounding font-size when omitted. */
    size?: number;
    /** Theme text colour. Inherits the surrounding colour (currentColor) when omitted. */
    color?: TextColorToken;
} & Omit<React.HTMLAttributes<HTMLElement>, "children" | "color">;
export declare const Icon: React.ForwardRefExoticComponent<{
    name: UiIconName;
    /** Glyph size in px (sets font-size). Inherits the surrounding font-size when omitted. */
    size?: number;
    /** Theme text colour. Inherits the surrounding colour (currentColor) when omitted. */
    color?: TextColorToken;
} & Omit<React.HTMLAttributes<HTMLElement>, "color" | "children"> & React.RefAttributes<HTMLElement>>;
/**
 * Icon-font glyph. Sized by `size`/font-size, colored by `color`/currentColor;
 * decorative by default (aria-hidden) — pass aria-hidden={false} plus a label
 * on the parent control when the icon is the only content.
 */
